enable: false

# Used for authentication and plugin licensing (limited time)
plugin:
  secretKey:
  token:

# Database support
# - SQLite
database:
  type: sqlite

  sqlite:
    path: artificialintelligence.db

token:
  # Used to encrypt player tokens before saving them to the database
  # Must have a length of 16 characters
  secretKey:

# Token for checking plugin version from GitHub releases
gtihub:
  token:

ai:
  custom:
    # You can define multiple servers under "custom"
    # Each server can have its own URL, token, and default model

    server1:
      # API endpoint URL for server1
      url: http://localhost:11434/v1/chat/completions
      # Authorization token for server1
      token:
      # Default model name for server1
      models:
        model1: model1

    server2:
      # API endpoint URL for server2
      url: http://localhost:11435/v1/chat/completions
      # Authorization token for server2
      token:
      # Default model name for server2
      models:
        model1: model1
        model2: model2

  deepseek:
    token:
    # Default model loaded when the plugin starts
    models:
      model1:

  openai:
    token:
    # Default model loaded when the plugin starts
    models:
      model1:

  openrouter:
    token:
    # Default model loaded when the plugin starts
    models:
      model1:
